### ISSUE TITLE
img.resize for 4bands image?

### ISSUE THREAD

**Issue by jovahe** [TachibanaYoshino/Remote-sensing-image-semantic-segmentation#1]
@TachibanaYoshino 
我看您用了PIL的resize函数对图像进行重采样，请问四波段影像是不是不能这样重采样？有没有什么好的方法进行重采样？
歇息
img, label = img.resize((c.size_train[1], c.size_train[0]), Image.ANTIALIAS), label.resize(
                    (c.size_train[1], c.size_train[0]), Image.BILINEAR)

**Comment by jovahe** [comment]
并且，觉得标签重采样后，边界有一定的问题，如下


![未命名图片](https://user-images.githubusercontent.com/17924267/62931822-881ed200-bdf1-11e9-9193-29bf8991cfb5.png)

**Comment by TachibanaYoshino** [comment]
The method of interpolation sampling generally changes the original data, no matter how many channels the input has. I have already verified this before. The change of the boundary value is in line with the actual situation. Different sampling methods will take values according to the adjacent area when scaling. If the difference between adjacent areas is large, the change of the boundary value will be large. You can think of this as an extra noise.

**Comment by jovahe** [comment]
@TachibanaYoshino thansk a lot. I have solved the multiband resizing problem, but I also fould the PlL resize() function only available for uint8 data type. If I want to deal with unint16 data type, the result would be wrong.

**Comment by jovahe** [comment]
I have fixed the problem of uint16 type as following:
            n_img = np.zeros((dst_h, dst_w, img.shape[-1]), np.uint16)
            img = np.asarray(img, np.uint32)
            for i in range(img.shape[-1]):
                b_img = img[:, :, i]
                b_img = Image.fromarray(b_img, mode='I')
                b_img = b_img.resize((dst_h, dst_w), mode)
                b_img = np.array(b_img, np.uint16)
                n_img[:, :, i] = b_img[:, :]
